server:
  port: 8080

spring:
  datasource:
    url: jdbc:derby:systemService;create=true
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    platform: derby
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show_sql: true
    use_sql_comments: true
    format_sql: true
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2192MB
      enabled: true

system-service:
  monitoring:
    system-information-script: /opt/scripts/get-system-information.sh

